### ISSUE TITLE
Potential race conditions on multi threaded server

### ISSUE THREAD

**Issue by vbarbaresi** [cpoisson/rent-a-bot#2] opened 2017-10-24 14:07 UTC
I don't see a locking mechanism on database operations.

If I run flask in threaded mode with `flask run --with-threads`, I can produce race conditions:
- We enter in `lock_by_id()` 2 times, and it succeeds to lock both times (to reproduce easily, add a sleep on the db operations in controller `lock_resource`)
- The resource has been locked twice and only the second response lock-token is valid.

Suggestion: use `threading.lock` or sqlite locks to make the app thread-safe

**Comment by cpoisson** [comment] 2017-10-24 19:41
Thanks! I'll definitely have a look a this.

It was one of my concerns, since I'm a bit new on this, I (naively) believed that some inner mechanism of SQLAlchemy would prevent this to happen using atomic thread safe operation on the DB. There is no magic I guess...

**Comment by cpoisson** [comment] 2017-10-24 20:13
Yup easily reproduced...

**Comment by cpoisson** [comment] 2017-10-24 21:18
Fixed on master with https://github.com/cpoisson/rent-a-bot/pull/3/commits/2887a914e9c5f5dad15a94bc06719e62cbc9098d

It made me discover that I should refactor the controller to make it more thread safe tough...

**Closed by cpoisson** 2017-10-24 21:18 UTC
